### ISSUE TITLE
gnome 3.32 support

### ISSUE THREAD

**Issue by daduke** [derekm/gnome-shell-open-terminal#5]
Hi,

I'm a heavy user of this extension on all my machines, only to discover it doesn't work on gnome 3.32 (Fedora 30) any more (3.32 patched into metadata.json of course)! The menu item simply doesn't show up. I spent the last hour trying to figure out if and how the gnome shell ui.backgroundMenu magic has changed, but gnome shell documentation is not exactly easy to find. Do you happen to remember what you used back in 2014?

thanks,
-Christian

**Comment by derekm** [comment]
I had to read the source code myself to make sense of things and to find the extension points where I could monkeypatch the behavior, etc.!

Probably not the answer you were looking! But I'd love to help you make progress!

One issue where I got discouraged was keeping the plugin compatible with old, intermediate and new versions. ... If you'll be compensating for breaking changes, we need to find exactly which version those behaviors broke in so that the manifest and the code can indicate and achieve proper compatibility for all releases.

So glad you love the extension! I'm a usability nerd, so I really like simple usability enhancements such as this plugin.

Let me know how if I can help... I should get back into using Linux regularly... I've been relying too heavily on the walled-ghetto of macOS and its somewhat archaic UNIX environment.

Thanks again for the feedback! Good luck, I think you can figure it out!

Cheers,
Derek

**Comment by daduke** [comment]
> I had to read the source code myself to make sense of things and to find the extension points where I could monkeypatch the behavior, etc.!

uhm ok, I guess that's always an option :)


> One issue where I got discouraged was keeping the plugin compatible with old, intermediate and new versions. ... If you'll be compensating for breaking changes, we need to find exactly which version those behaviors broke in so that the manifest and the code can indicate and achieve proper compatibility for all releases.

I agree, but I for one wouldn't care about older versions, I just need it working again on 3.32.
It was still working on F29's gnome 3.30 (I just now realize, even w/o having 3.30 in the manifest..), but with the upgrade it broke.


> Let me know how if I can help... I should get back into using Linux regularly... I've been relying too heavily on the walled-ghetto of macOS and its somewhat archaic UNIX environment.

well if you take this opportunity to come back to Linux, we both won :)

thanks, I'll probably try gnome IRC and read the source.

cheers,
-Christian

**Comment by kstange** [comment]
I just checked here on a whim and ended up finding this thread...

I literally just forked and fixed GNOME 3.32 support earlier today.  I dropped everything prior to 3.30 because I have no plans to run multiple old versions of GNOME for testing.  I implemented the menu item insertion differently after spending a while digging through the upstream JS for PopupMenu, BackgoundMenu and LayoutManager.  It's possible that this method works on older versions of GNOME because it doesn't mess with the class constructor which is the major thing that changed in 3.32.

I submitted a new package here because I assumed this one was abandoned.

https://extensions.gnome.org/review/10492

Here's my fork with commits from today:

https://github.com/kstange/gnome-shell-open-terminal

**Comment by daduke** [comment]
> I just checked here on a whim and ended up finding this thread...
> 
> I literally just forked and fixed GNOME 3.32 support earlier today. I dropped everything 3.30 and prior because I have no plans to run multiple old versions of GNOME for testing. I implemented the menu item insertion differently after spending a while digging through the upstream JS for PopupMenu, BackgroundMenu and LayoutManager. It's possible that this method works on older versions of GNOME because it doesn't mess with the class constructor which is the major thing that changed in 3.32.
> 
> I submitted a new package here because I assumed this one was abandoned.
> 
> https://extensions.gnome.org/review/10492
> 
> Here's my fork with commits from today:
> 
> https://github.com/kstange/gnome-shell-open-terminal

you are my hero! It verks! Thanks so much, made my day.

**Comment by kstange** [comment]
> you are my hero! It verks! Thanks so much, made my day.

I noticed that my extension doesn't work properly at login so you have to toggle it on and off.  I'm assuming enable gets run before the desktops are initialized so I'll have to fix that.

**Comment by daduke** [comment]
I did notice that, but I thought it was because of how I had installed the extension (manual unzip). Another reason to never log out and just suspend :)

**Comment by derekm** [comment]
@daduke -- The benefit of you hosting the fork is both versions of the plugin can be available to users without the plugin itself being version aware. Otherwise, the extension model doesn't well-support different impls for different GNOME Shell versions without the plugin itself introspecting what version it is presently running on. I'd like to collect all latest changes here, even if you and others host the final builds for specific versions beyond the early version I published.

**Comment by djast** [comment]
In case anyone else needs a workaround, I believe I've found that the plugin can be made to work at login by moving the work of enable() to a timeout:

```
--- gnome-shell-open-terminal-master/extension.js	2019-05-06 14:39:44.000000000 -0400
+++ /usr/share/gnome-shell/extensions/gnome-shell-open-terminal@kstange.github.com/extension.js	2020-04-07 16:14:23.322958883 -0400
@@ -21,6 +21,13 @@
     }
 
     enable() {
+	imports.mainloop.timeout_add(1, () => {
+	    this.do_enable();
+	    return false;
+	});
+    }
+
+    do_enable() {
         PopupMenu.PopupMenu.prototype.addActionAt = function(title, position, callback) {
             let menuItem = new PopupMenu.PopupMenuItem(title);
             this.addMenuItem(menuItem, position);
```
I'm guessing this works because it defers execution until the main loop has initialized, but I don't pretend to understand the details here--it may not be the most elegant fix, but it appears to be working for me.
